# Generated by Django 4.2.3 on 2023-07-21 14:38
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def create_groups(apps, schema_migration):
    emit_post_migrate_signal(2, False, 'default')
    User = apps.get_model('administration', 'MyUser')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    delete_client = Permission.objects.get(codename='delete_client')
    view_client = Permission.objects.get(codename='view_client')

    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    delete_contract = Permission.objects.get(codename='delete_contract')
    view_contract = Permission.objects.get(codename='view_contract')

    add_event = Permission.objects.get(codename='add_event')
    change_event = Permission.objects.get(codename='change_event')
    delete_event = Permission.objects.get(codename='delete_event')
    view_event = Permission.objects.get(codename='view_event')

    add_myuser = Permission.objects.get(codename='add_myuser')
    change_myuser = Permission.objects.get(codename='change_myuser')
    delete_myuser = Permission.objects.get(codename='delete_myuser')
    view_myuser = Permission.objects.get(codename='view_myuser')

    view_permission = Permission.objects.get(codename='view_permission')
    view_group = Permission.objects.get(codename='view_group')

    administrator_permissions = [
        view_event,
        add_event,
        change_event,
        delete_event,
        view_client,
        delete_client,
        add_client,
        change_client,
        delete_contract,
        change_contract,
        view_contract,
        add_contract,
        view_group,
        view_permission,
        change_myuser,
        delete_myuser,
        add_myuser,
        view_myuser
    ]

    commercial_permissions = [
        view_contract,
        add_contract,
        add_event,
        view_client,
        change_client,
        change_event,
        change_contract,
        view_event,
        add_client
    ]
    support_permissions = [
        view_client,
        view_contract,
        change_event,
        view_event
    ]

    administrator = Group(name='administrator')
    administrator.save()
    administrator.permissions.set(administrator_permissions)
    commercial = Group(name='commercial')
    commercial.save()
    commercial.permissions.set(commercial_permissions)
    support = Group(name='support')
    support.save()
    support.permissions.set(support_permissions)

    for user in User.objects.all():
        if user.role == 'administrator':
            administrator.user_set.add(user)
        if user.role == 'commercial':
            commercial.user_set.add(user)
        if user.role == 'support':
            support.user_set.add(user)


class Migration(migrations.Migration):
    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
