# Generated by Django 4.2.3 on 2023-07-26 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25, verbose_name='first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='office phone')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='mobile')),
                ('company_name', models.CharField(max_length=25, verbose_name='company name')),
                ('existing', models.BooleanField(default=False, verbose_name='existing')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date updated')),
                ('sales_contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='sales contact')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='amount')),
                ('payment_due', models.DateField(blank=True, null=True, verbose_name='payment due')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date updated')),
                ('client', models.ForeignKey(limit_choices_to={'existing': True}, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='client')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_status', models.BooleanField(default=True, verbose_name='status')),
                ('attendees', models.PositiveIntegerField(blank=True, null=True, verbose_name='attendees')),
                ('location', models.TextField(blank=True, verbose_name='location')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='event date')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateField(auto_now=True, verbose_name='date updated')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.contract', verbose_name='contract')),
                ('support_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='support contact')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('client', 'date_created'), name='unique_contract_by_day'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name', 'company_name'), name='unique_full_name'),
        ),
    ]
