# Generated by Django 4.2.2 on 2023-07-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_mobile_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='adresse électronique'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=25, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=25, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='office phone'),
        ),
    ]
